# Generated by Django 4.1.2 on 2022-10-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',), 'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
